title: 'Tom Donoghue, PhD'
description: 'Some kind of Cognitive (Neuro?) Scientist'

name: 'Tom Donoghue'
url: https://tomdonoghue.github.io

theme: jekyll-theme-cayman

# Google analytics services
google_analytics: UA-93965597-1

twitter_username:     TomDonoghue
github_username:      TomDonoghue

# Options for kramdown markdown
kramdown:
  # Set which header levels get included in TOC
  toc_levels: 2..2