title: 'Tom Donoghue'
description: 'Some kind of Cognitive (Neuro?) Scientist (in training)'

name: 'Tom Donoghue'
url: https://tomdonoghue.github.io

theme: jekyll-theme-cayman

# Google analytics services
google_analytics: UA-93965597-1

#
twitter_username:     TomDonoghue
github_username:      TomDonoghue