title: 'Tom Donoghue'
description: 'Some kind of Cognitive (Neuro?) Scientist'

name: 'Cognitive Musings'
url: https://tomdonoghue.github.io

#theme: minima
theme: jekyll-theme-cayman

#
twitter_username:     TomDonoghue
github_username:      TomDonoghue